name: collect-signals

on:
  schedule:
    - cron: '*/5 13-20 * * 1-5'  # Every 5 mins during US market hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run market signals bot
        run: python main.py
        env:
          REDDIT_ID: ${{ secrets.REDDIT_ID }}
          REDDIT_SECRET: ${{ secrets.REDDIT_SECRET }}
          REDDIT_USERAGENT: ${{ secrets.REDDIT_USERAGENT }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FINNHUB_KEY: ${{ secrets.FINNHUB_KEY }}

      - uses: EndBug/add-and-commit@v9
        with:
          message: "auto: update signals"
          add: "signals.*"
          default_author: github_actions

      - name: Pull remote to fast-forward if needed
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull --ff-only || true
